baseURL = "https://quoc-khanh-123.github.io/blog-lap-trinh-mang/"
languageCode = "vi"
title = "Blog Lập Trình Mạng"
theme = "PaperMod"
publishDir = "docs"

[params]
  author = "Tên của bạn"
  defaultTheme = "light"
  disableThemeToggle = true

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[params.profileMode]
  enabled = true
  title = "Blog Lập Trình Mạng"
  subtitle = "Chia sẻ kiến thức Java & JavaScript về lập trình mạng"
  imageUrl = "images/avatar.jpg"

  [[params.profileMode.buttons]]
    name = "Bài viết"
    url = "/posts/"

  [[params.profileMode.buttons]]
    name = "Profile"
    url = "/profile/"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Profile"
    url = "/profile/"
    weight = 3
